### ISSUE TITLE
Error using gcc 8.1.0 on Ubuntu 14.04

### ISSUE THREAD

**Issue by gilgameshskytrooper** [nlohmann/json#1207]
- What is the issue you have?
Using the default Ubuntu build environment for `cpp` on Travis-CI, I am getting a `#unsupported GCC version` despite installing `gcc-8` from the `ubuntu-toolchain-r-test` apt repository and setting the cmake C++ compiler to use g++ 8.1.0 (by setting it in the command line options via `cmake -D -CMAKE_CXX_COMPILER="/usr/bin/cpp-8"`).

The result of `cpp-8 --version` is:
```
cpp-8 (Ubuntu 8.1.0-5ubuntu1~14.04) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Furthermore, swapping `"/usr/bin/cpp-8"` with `"/usr/bin/gcc-8"` gives me the same error.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

1. Create a new Github repository and hook it up to Travis CI.
2. Define the environment variables `VIAPIKEY` and `VIAPITOKEN` in the repository's environment variables by signing up for a free account on my company's website [voiceit.io](voiceit.io) API version 2.
3. In your repository, do the following:
```
wget https://raw.githubusercontent.com/voiceittech/voiceit2-cpp/master/Test.cpp
wget https://raw.githubusercontent.com/voiceittech/voiceit2-cpp/master/VoiceIt2.hpp
wget https://raw.githubusercontent.com/voiceittech/voiceit2-cpp/master/json.hpp
```
4. Add a `.travis.yml` as follows:
```
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - libssl-dev
      - cmake
before_script:
  - git submodule add https://github.com/whoshuu/cpr.git
  - git submodule update --init --recursive
  - echo "set (CMAKE_CXX_STANDARD 11)" > CMakeLists.txt
  - echo "project (Tests)" >> CMakeLists.txt
  - echo "cmake_minimum_required(VERSION 2.8.12)" >> CMakeLists.txt
  - echo "add_subdirectory(cpr)" >> CMakeLists.txt
  - echo "include_directories(\${CPR_INCLUDE_DIRS})" >> CMakeLists.txt
  - echo "add_executable(Tests Test.cpp)" >> CMakeLists.txt
  - echo "target_link_libraries(Tests \${CPR_LIBRARIES})" >> CMakeLists.txt
  - gcc-8 --version
  - cpp-8 --version
  - cmake -D -CMAKE_CXX_COMPILER="/usr/bin/gcc-8"
  - make
script: "./Tests"
```
5. `git add . && git commit -m "message" && git push origin master`
***Note: The reason you aren't just going to fork the project is because Travis is kind of a pain to set up on forked repos.***

- What is the expected behavior?
No compiler error since we are using gcc 8.1.0

- And what is the actual behavior instead?
`error: #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"`
- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
```
cpp-8 (Ubuntu 8.1.0-5ubuntu1~14.04) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
on Ubuntu 14.04 LTS.

Also tried setting it to use `gcc-8` instead of `cpp-8` which is version:
```
gcc-8 (Ubuntu 8.1.0-5ubuntu1~14.04) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
which should be in the range of gcc 4.9 ~ gcc 8.2

- Did you use a released version of the library or the version from the `develop` branch?

No I specifically used version 3.1.2 since the new 3.2.0 version increased the number of dependencies for my project (`json_fwd.hpp`).

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

check out [the logs for my Travis CI build](https://travis-ci.org/voiceittech/voiceit2-cpp/builds/418799343). Specifically, search the page for "gcc-8 --version" which will show the gcc version. The error might not actually show up unless you check out the [raw logs](https://api.travis-ci.org/v3/job/418799344/log.txt).
